apiVersion: v1
kind: Pod
metadata:
    name: kubia-manual-v2
    labels:
      creation_method: manual
      app: kubia
spec:
    containers:
    - image: jundol/kubia
      name: kubia
      ports:
      - containerPort: 8080
        protocol: TCP
