apiVersion: v1
kind: Pod
metadata:
 name: kubia-gpu
spec:
 affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: gpu
        operator: In
        values:
        - "true"
 containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0



