apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: shoppingcart-netpolicy
spec:
 podSelector:
  matchLabels:
   app: shopping-cart
 ingress:
 - from: 
   - ipBlock:
      cidr: 192.168.1.0/24
   ports:
   - port: 80
